### ISSUE TITLE
Remove position correction broke PV5.1 conversion

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/bruker#10]
Hi,

This commit
https://github.com/BrkRaw/bruker/commit/686036aa1115d5f5c1c82dd787ba1174268fed5f

Broke the PV5.1 orientation. I now get my mouse-phatom converted backward.

**Comment by gdevenyi** [comment]
0.3.3rc0:
![image](https://user-images.githubusercontent.com/3001850/83907472-71a48700-a733-11ea-801a-67b4ac44c93e.png)


HEAD (0.3.3)
![image](https://user-images.githubusercontent.com/3001850/83907527-8ed95580-a733-11ea-9c8d-97ff67dbb123.png)

**Comment by gdevenyi** [comment]
Scans collected on PV6 seem to work properly.

**Comment by dvm-shlee** [comment]
@gdevenyi  Thank you for reporting!
Yeah, I forgot there was the reason that I've added the position correction.
Currently, I made a quick patch to correct the subject position on PV5.
Please let me know if this does not properly work.
(version 0.3.4b0, but does not update on PyPi yet)

Thank you!

**Comment by gdevenyi** [comment]
Things, commit has fixed things.

Can you please git tag all your rc releases so they're easier to test against? Thanks.

**Comment by dvm-shlee** [comment]
@gdevenyi  That's a great suggestion,
Still learning the way working with GitHub. 
Will tag including the all prerelease as well for the future.

Thanks!

**Comment by gdevenyi** [comment]
Hi, I need to reopen this and apologize. It seems that all of our data has been collected incorrectly as "Head First Supine" as such your original conversion was correct and you should revert 
7aaa7e8

**Comment by dvm-shlee** [comment]
@gdevenyi This is reverted, Thank you for letting me know! I will close this issue.
