### ISSUE TITLE
Could SimpleITK become an optional dependency?

### ISSUE THREAD

**Issue by mih** [BrkRaw/bruker#17]
Hey, this issue is part of my review of your JOSS submission at https://github.com/openjournals/joss-reviews/issues/2277

SimpleITK is a quite heavy (>40MB) and needs to be compiled (in contrast to the pure Python NiBabel). Moreover, it is only used in a single location `lib/loader.py:get_sitkimg()` via an internal import.

Could this be made an optional dependency and safe non-ITK users the potential complications?

**Comment by gdevenyi** [comment]
https://github.com/BrkRaw/bruker/blob/master/brkraw/lib/loader.py#L356-L405

**Comment by dvm-shlee** [comment]
@mih This is the good point, I will try to find a way to make it optional and revise the script.
