### ISSUE TITLE
LICENSE file contains more than one license (merge-conflict left-over)

### ISSUE THREAD

**Issue by mih** [BrkRaw/bruker#18]
Hey, this issue is part of my review of your JOSS submission at openjournals/joss-reviews#2277

It starts like this:

```
<<<<<<< HEAD
                    GNU GENERAL PUBLIC LICENSE
=======
                   GNU LESSER GENERAL PUBLIC LICENSE
>>>>>>> 293c218a6d432b192fba6d65b22d9dc843cb1c7e
```

but the entire file seems to be affected.

**Comment by dvm-shlee** [comment]
@mih Thank you to point out! I did not aware! I will correct on the revised version. Thank you!

**Comment by dvm-shlee** [comment]
@mih Its corrected! Thanks!
