### ISSUE TITLE
PV6 VisuSubjectType is not used to provide proper orientation in combination with VisuSubjectPosition

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/bruker#25]
In the case of PV6, there are several options for input subject type:
![image](https://user-images.githubusercontent.com/3001850/87456416-e5f50480-c5d4-11ea-9abc-2122ac8ffb60.png)

When combined with VisuSubjectPosition, these need to properly orient the scan in standardized coordinates.

Take for example a primate in "Head First Supine" vs a Rodent in "Head First Supine", the brain will be rotated by 90 degrees relative to each other.

This will also probably require some special casing for PV5, as it does not seem to have an option to set this parameter and always specifies ``SUBJECT_type=Human``

**Comment by dvm-shlee** [comment]
@gdevenyi It actually integrated but just not thoroughly tested, so I'm not sure it works correctly,
Currently, I only have a dataset with Quadruped but apply -90 degree on X-axis and 180 degrees for Y-axis to correct the orientation.
The code is located at `brkraw.lib.utils.build_affine_from_orientation_info`
In case this is not functioning as you expected, could you provide any sample that shows the issue?

**Comment by gdevenyi** [comment]
Ah sorry, I see you have some corrections. I've gotten confused as the scanner console does not have the same options as the code and I was searching for the scanner options in the source.

I think for Other (and maybe Phantom) no correction should be applied? I'm pretty sure the orientation settings are disabled at the console. As for OtherAnimal, at least for their example a snake has the same brain-to-body geometry as a quadruped.

As I mentioned elsewhere I'm collecting a complete dataset of a phantom with all the various settings flipped around in combinations to test all configs.
