### ISSUE TITLE
Naming convention of output file using brkraw tonii

### ISSUE THREAD

**Issue by hille** [BrkRaw/bruker#31]
Hey! I am trying to use brkraw to convert my raw files to nifti. 
Unfortunately, within my subject file the values for SubjectID, SessionID and StudyID seem to be weirdly assigned. I am now modyfining those values so that the output after conversion is named clearly and correctly. As far as I understand the files coming from the conversion (when using brkraw tonii) are named according to what is written in the subject-file of each scan. Could you tell me which values are used to form the name of the output file? 
Thank you for your help!

**Comment by dvm-shlee** [comment]
Hi @hille 
If you use 'tonii' option to convert, as default, it uses,

'SUBJECT_id' and 'SUBJECT_study_nr' values from subject file.
But with -o option, you can specify your own.

**Comment by hille** [comment]
Hi, thank you for the fast reply!
I was wondering what else except for those two values that you mentioned is included into the file name because when converting my file, it is named "SUBJECT_id_SUBJECT_study_nr-01-1.nii.gz". Could you tell me where the "-01-1" comes from and how to change that?

**Comment by gdevenyi** [comment]
The naming is constructed here:
https://github.com/BrkRaw/bruker/blob/master/brkraw/scripts/brkraw.py#L136

So those numbers correspond to scan_id and reco_id from the study

**Comment by gdevenyi** [comment]
There is no way to currently change that naming, as those numbers are needed to guarantee unique naming for every file from inside the bruker dataset.

**Comment by hille** [comment]
Thanks for your answer! Where does reco_id and scan_id come from? Are the values taken somewhere from the subject-file / a different file from the bruker raw files or are those default-values that are set from the brkraw tool?

**Comment by gdevenyi** [comment]
The `scan_id` refers to order of the scan as collected during the session, and the `reco_id` refers to the number of reconstruction (typically only 1 reconstruction, but additional ones can be done in special cases)

**Comment by hille** [comment]
Thanks, that helps a lot!
