### ISSUE TITLE
the "-r" in the description of using brkraw bids_convert description is not consistent with brkraw.py , which is "-j"

### ISSUE THREAD

**Issue by Jetgc** [BrkRaw/bruker#34]
**Describe the bug**
the "-r" in the description of using 

> brkraw bids_convert <input dir> <BIDS datasheet.xlsx> -r <JSON syntax template.json> -o <output dir>

 is not consistent with the code of brkraw.py , which is "-j"

**Comment by dvm-shlee** [comment]
Thank you for the correction, just updated it.
