### ISSUE TITLE
bruker 0.3.6 no longer on pip? 

### ISSUE THREAD

**Issue by grandjeanlab** [BrkRaw/bruker#35]
**Describe the bug**
~2 months ago, `pip insall bruker` would install 0.3.6
Today, only 0.3.3 is available.  

Contrary to 0.3.6 , the currently available version doesn't attribute axis orientation correctly for head-first prone mice that were labelled on scan card as being 'supine' (AKA: the trick).  

**To Reproduce**
conda create --name bruker pip
source activate bruker
pip install bruker
pip list | grep bruker

Current output (12-02-2021:
bruker                   0.3.3

**Expected behavior**
On my build (late 2020): 
bruker                   0.3.6

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: CentOS Linux 7 (Core)
 - Python 3.7.9
 - pip 20.3.3

**Additional context**

**Comment by gdevenyi** [comment]
`pip install https://github.com/BrkRaw/bruker/archive/0.3.4.tar.gz` will directly install from the releases on github

**Comment by grandjeanlab** [comment]
:100: :fire: :fire: @gdevenyi
