### ISSUE TITLE
website bids converter tutorial Jupyter Notebooks link broken

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/bruker#37]
**Describe the bug**
Jupyter Notebooks link on bottom of the [bids converter page](https://brkraw.github.io/docs/gs_bids.html) is borken

**To Reproduce**
1. Go to [bids converter page](https://brkraw.github.io/docs/gs_bids.html)
2. Click on 'Jupyter Notebooks'
3. See error 404

To fix, update the link or remove it.

**Comment by dvm-shlee** [comment]
@ycAbout  Thank you for checking out! I just fixed it!
