### ISSUE TITLE
3D FLASH T1w slope

### ISSUE THREAD

**Issue by egarza** [BrkRaw/bruker#7]
Hi again,

This is another issue that drove us crazy when using DICOMS. Seems the intensity range in the Bruker 3D FLASH T1w is from 0-1. We usually just removed the 2 first lines in the following DICOM header options to fix it:

```
0028 1052        2 [1870    ] //          IMG Rescale Intercept//0 
0028 1053       16 [1880    ] //              IMG Rescale Slope//0.0001033734821 
0028 1054        2 [1904    ] //               IMG Rescale Type//US
```
This is also true for the GRE-EPI data:

```
0028 1052        2 [1834    ] //          IMG Rescale Intercept//0 
0028 1053       12 [1844    ] //              IMG Rescale Slope//0.0073491817
0028 1054        2 [1864    ] //               IMG Rescale Type//US
```

Is there a way to Convert the file with the full range?

Thank you,

Eduardo

**Comment by dvm-shlee** [comment]
@egarza It seems what you are asking is the way to remove data slope.

I just add the option --ignore_slope
just add it to your command. such as
To use this new option, please update with the command below
```pip install --upgrade git+https://github.com/brkraw/bruker```
then 
```brkraw gui --ignore_slope```
or 
```brkraw tonii --ignore_slope <raw data path>```

Hope this can solve your issue.

**Comment by dvm-shlee** [comment]
@egarza Since I had an additional update, you can use this function from 0.3.3rc8

**Comment by egarza** [comment]
Great! thanks again

**Comment by dvm-shlee** [comment]
Could you close this issue if you don't have any problem with the new option? Thank you!

**Comment by gdevenyi** [comment]
I think if its not already there --ignore-offset should go with this.

**Comment by dvm-shlee** [comment]
@gdevenyi I've already made the changes but if the term --ignore-offset is more suitable, I will update it for 0.3.3 release version.

Thank you for your comment!

**Comment by gdevenyi** [comment]
sorry, thats not what I mean. The bruker specifies a scaling as an offset + a slope to remap the on-disk data into a different data range. If we have an --ignore-slope parameter, we should also have an --ignore-offset parameter

**Comment by gdevenyi** [comment]
See https://github.com/SebastianoF/bruker2nifti/blob/6cf20451a135e9d001a39ad2bd6efc81c253c609/bruker2nifti/_cores.py for example

**Comment by dvm-shlee** [comment]
@gdevenyi I got what your point now. The reason I only handled this is before I haven't seen any offset value assigned on Bruker data so far. And these two would be better to go together since it's just for correcting the value into the data type (16bit) by combining two (slope and offset). 

So if there is any good idea to cover both (for example --ignore-correction), it would be more suitable I think?

**Comment by gdevenyi** [comment]
I think we should try to implement the spec as-is, even if we've never seen values for some things. This kind of correction is important for quantitative acquisions.

I think rather, I'd like three options
--ignore-slope
--ignore-offset
--ignore-rescaling

Where --ignore-rescaling disables both.

**Comment by dvm-shlee** [comment]
@gdevenyi It makes sense to me. I will implement those three options on the next update. Thank you for the suggestion!

**Comment by egarza** [comment]
Thank you, that would help a lot. This is a big issue specially for volumetric analysis.

**Comment by dvm-shlee** [comment]
@gdevenyi  @egarza 0.3.3 released version will have those functions.
--ignore-rescale, or --ignore-slope and --ignore-offset
I will close this issue, but please let me know if other issues occurred related to this change.
